export const originalRecipes = [
    {
        recipeName: "Penne Bake w/ Italian Sausage",
        difficulty: 1,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Penne Pasta", form: "Dry (packaged)", quantity: "40 lb" },
            { name: "Italian Sausage", form: "Fresh (in casing)", quantity: "30 lb" },
        ],
        notes:
            "A hearty pasta bake with a rich tomato sauce. Ideal for a large family dinner.",
        vegan: "Plant‐based sausage (1 lb)",
        vegetarian: "Roasted mixed vegetables and mushrooms (1 lb)",
        glutenFree: "Gluten‐free pasta (1 lb)",
        recommendedSides: "Garlic Bread",
        recommendedBread: "",
        recommendedSalad: "Caesar Salad",
        recommendedDessert: "Tiramisu",
        createdBy: "",
    },
    {
        recipeName: "Spaghetti w/ Bolognese",
        difficulty: 1,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Spaghetti", form: "Dry (packaged)", quantity: "40 lb" },
            { name: "Ground Beef", form: "Fresh (ground)", quantity: "20 lb" },
            { name: "Tomato Sauce", form: "Canned", quantity: "80 cups" },
            { name: "Onion", form: "Fresh", quantity: "40 cups" },
        ],
        notes:
            "A classic spaghetti with a hearty meat sauce suitable for large groups.",
        vegan: "Lentils (1 lb)",
        vegetarian: "Mushrooms and lentils (1 lb)",
        glutenFree: "Gluten‐free spaghetti (1 lb)",
        recommendedSides: "Garlic Bread",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName: "Lasagna",
        difficulty: 4,
        cost: 4,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Lasagna Noodles", form: "Dry (packaged)", quantity: "480 pieces" },
            { name: "Ricotta", form: "Fresh", quantity: "80 cups" },
            { name: "Mozzarella", form: "Pre‐shredded", quantity: "80 cups" },
            { name: "Ground Beef", form: "Fresh (ground)", quantity: "40 lb" },
        ],
        notes:
            "Layers of pasta, meat, and cheese baked to perfection for a crowd.",
        vegan: "Vegan cheese (1 lb) and grilled vegetables (1 lb)",
        vegetarian: "Mushrooms and spinach (1 lb)",
        glutenFree: "Gluten‐free lasagna noodles (17 pieces)",
        recommendedSides: "Garlic Bread",
        recommendedBread: "",
        recommendedSalad: "Green Salad",
        recommendedDessert: "Cannoli",
        createdBy: "",
    },
    {
        recipeName: "Chicken Parm",
        difficulty: 3,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Chicken Breast", form: "Fresh (skinless, boneless)", quantity: "80 pieces" },
            { name: "Marinara Sauce", form: "Canned", quantity: "40 cups" },
            { name: "Mozzarella", form: "Pre‐sliced", quantity: "20 lb" },
        ],
        notes:
            "Classic chicken parmesan with breaded chicken and melted cheese.",
        vegan: "Eggplant slices or tofu (3 pieces) and vegan cheese (1 lb)",
        vegetarian: "Eggplant or portobello mushrooms (3 pieces)",
        glutenFree: "Gluten‑free breadcrumbs (as per recipe)",
        recommendedSides: "",
        recommendedBread: "",
        recommendedSalad: "Caesar Salad",
        recommendedDessert: "Gelato",
        createdBy: "",
    },
    {
        recipeName: "Cold Cut/Meatball Subs",
        difficulty: 1,
        cost: 2,
        month: 7,
        meal: "dinner",
        ingredients: [
            { name: "Italian Cold Cuts", form: "Assorted (deli style)", quantity: "20 lb" },
            { name: "Meatballs", form: "Pre‐cooked", quantity: "160 pieces" },
            { name: "Sub Rolls", form: "Fresh bakery", quantity: "160 rolls" },
            { name: "Lettuce", form: "Fresh", quantity: "40 cups" },
            { name: "Tomato", form: "Fresh", quantity: "40 tomatoes" },
            { name: "Onion", form: "Fresh", quantity: "40 onions" },
        ],
        notes:
            "Delicious subs loaded with cold cuts and meatballs, perfect for lunch.",
        vegan: "Plant‐based deli slices (1 lb) and vegan meatballs (6 pieces)",
        vegetarian: "Grilled vegetables and cheese (1 lb)",
        glutenFree: "Gluten‑free sub rolls (6 rolls)",
        recommendedSides: "Chips",
        recommendedBread: "",
        recommendedSalad: "Coleslaw",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName: "Pulled Pork Sandwiches w/ Roasted Potatoes & Veg",
        difficulty: 3,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Pulled Pork", form: "Fresh (slow‐cooked)", quantity: "40 lb" },
            { name: "Potatoes", form: "Fresh (raw)", quantity: "80 lb" },
            { name: "Mixed Vegetables", form: "Fresh", quantity: "40 lb" },
        ],
        notes:
            "Tender pulled pork served with crispy roasted potatoes and steamed veggies.",
        vegan: "Jackfruit or BBQ tofu (1 lb)",
        vegetarian: "Portobello mushrooms (1 lb)",
        glutenFree: "",
        recommendedSides: "Coleslaw",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "Brownies",
        createdBy: "",
    },
    {
        recipeName: "Hamburgers/Hot Dogs w/ Fries & Onion Rings",
        difficulty: 3,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Hamburger Patties", form: "Fresh (ground beef)", quantity: "160 patties" },
            { name: "Hot Dogs", form: "Packaged", quantity: "160 hot dogs" },
            { name: "Fries", form: "Frozen", quantity: "40 lb" },
            { name: "Onion Rings", form: "Frozen", quantity: "40 servings" },
        ],
        notes:
            "A fun mix of burgers, hot dogs, fries, and onion rings perfect for a crowd.",
        vegan: "Plant‐based patties (6 patties) and vegan hot dogs (6 pieces)",
        vegetarian: "Veggie patties (6 patties)",
        glutenFree: "",
        recommendedSides: "Pickles",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "Ice Cream",
        createdBy: "",
    },
    {
        recipeName: "Sloppy Joes on Fresh Buns",
        difficulty: 2,
        cost: 2,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Ground Beef", form: "Fresh (ground)", quantity: "40 lb" },
            { name: "Sloppy Joe Sauce", form: "Canned", quantity: "40 cups" },
            { name: "Fresh Buns", form: "Bakery", quantity: "160 buns" },
        ],
        notes: "Messy and delicious sloppy joes that are easy to serve.",
        vegan: "Textured vegetable protein (1 lb)",
        vegetarian: "Lentils and mushrooms (1 lb)",
        glutenFree: "Gluten‑free buns (6 buns)",
        recommendedSides: "Potato Chips",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName: "(Vegetarian) Chilli Cheese Dogs",
        difficulty: 2,
        cost: 2,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Veggie Dogs", form: "Packaged", quantity: "160 veggie dogs" },
            { name: "Chilli", form: "Canned", quantity: "40 cups" },
            { name: "Cheddar Cheese", form: "Pre‐shredded", quantity: "40 cups" },
        ],
        notes:
            "A twist on hot dogs featuring a spicy chilli and melted cheese.",
        vegan: "Soy‐based veggie dogs (6 pieces) and vegan cheese (1 cup)",
        vegetarian: "Already vegetarian",
        glutenFree: "",
        recommendedSides: "Fries",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName: "Korean Beef w/ Shredded Carrot, Rice & Bok Choi",
        difficulty: 3,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Beef", form: "Fresh (sliced, marinated)", quantity: "40 lb" },
            { name: "Carrot", form: "Fresh", quantity: "40 cups" },
            { name: "Rice", form: "Dry (packaged)", quantity: "80 cups" },
            { name: "Bok Choi", form: "Fresh", quantity: "40 bunches" },
        ],
        notes:
            "A flavorful dish with marinated beef and crisp vegetables.",
        vegan: "Marinated tofu (1 lb)",
        vegetarian: "Mushrooms and tofu (1 lb)",
        glutenFree: "",
        recommendedSides: "Kimchi",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "Mochi",
        createdBy: "",
    },
    {
        recipeName:
            "Cabbage & Sweet & Salty (Ground) Pork on Rice w/ Shredded Carrot",
        difficulty: 3,
        cost: 2,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Ground Pork", form: "Fresh (raw)", quantity: "40 lb" },
            { name: "Cabbage", form: "Fresh", quantity: "80 cups" },
            { name: "Carrot", form: "Fresh", quantity: "40 cups" },
            { name: "Rice", form: "Dry (packaged)", quantity: "80 cups" },
        ],
        notes: "A sweet and salty pork dish served over rice.",
        vegan: "Soy protein (1 lb)",
        vegetarian: "Mushrooms and lentils (1 lb)",
        glutenFree: "",
        recommendedSides: "Pickled Vegetables",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName: "Chicken Chow Mein w/ carrot, beansprout, something else green?",
        difficulty: 2,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Chicken", form: "Fresh (sliced)", quantity: "40 lb" },
            { name: "Chow Mein Noodles", form: "Dry (packaged)", quantity: "20 lb" },
            { name: "Carrot", form: "Fresh", quantity: "40 carrots" },
            { name: "Beansprouts", form: "Fresh", quantity: "80 cups" },
            { name: "Green Pepper", form: "Fresh", quantity: "40 peppers" },
        ],
        notes:
            "A stir‐fried noodle dish with crisp vegetables and tender chicken.",
        vegan: "Tofu (1 lb)",
        vegetarian: "Tofu and mushrooms (1 lb)",
        glutenFree: "Gluten‑free noodles (1 lb)",
        recommendedSides: "Egg Roll",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "Fortune Cookie",
        createdBy: "",
    },
    {
        recipeName: "Beef & Broccoli w/ egg fried rice",
        difficulty: 4,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Beef", form: "Fresh (sliced)", quantity: "40 lb" },
            { name: "Broccoli", form: "Fresh", quantity: "80 cups" },
            { name: "Egg Fried Rice", form: "Prepared", quantity: "120 cups" },
        ],
        notes:
            "A classic combination of beef, broccoli, and savory fried rice.",
        vegan: "Tofu (1 lb) and vegan egg substitute (1 lb)",
        vegetarian: "Extra vegetables and tofu (1 lb)",
        glutenFree: "Gluten‑free soy sauce (as needed)",
        recommendedSides: "Spring Rolls",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName: "Dumplings",
        difficulty: 4,
        cost: 2,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Ground Pork", form: "Fresh (seasoned)", quantity: "20 lb" },
            { name: "Cabbage", form: "Fresh", quantity: "40 cups" },
            { name: "Dumpling Wrappers", form: "Dry (packaged)", quantity: "960 pieces" },
        ],
        notes:
            "Steamed dumplings filled with a savory pork mixture.",
        vegan: "Mushrooms and tofu (1 lb)",
        vegetarian: "Vegetables and tofu (1 lb)",
        glutenFree: "Gluten‑free dumpling wrappers (34 pieces)",
        recommendedSides: "Soy Sauce",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "Fortune Cookie",
        createdBy: "",
    },
    {
        recipeName: "Chicken, Broccoli, Cheesy Scalloped Potatoes",
        difficulty: 4,
        cost: 3,
        month: 5,
        meal: "dinner",
        ingredients: [
            { name: "Chicken", form: "Fresh (diced)", quantity: "40 lb" },
            { name: "Broccoli", form: "Fresh", quantity: "80 cups" },
            { name: "Scalloped Potatoes", form: "Prepared", quantity: "120 cups" },
        ],
        notes:
            "A hearty dish combining tender chicken, broccoli, and cheesy potatoes.",
        vegan: "Chickpeas (1 lb) and vegan cheese (1 lb)",
        vegetarian: "Extra potatoes and vegetables (1 lb)",
        glutenFree: "",
        recommendedSides: "",
        recommendedBread: "",
        recommendedSalad: "Green Salad",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName: "Chili con Carne & Loaded Baked Potatoes",
        difficulty: 3,
        cost: 3,
        month: 5,
        meal: "dinner",
        ingredients: [
            { name: "Ground Beef", form: "Fresh (ground)", quantity: "40 lb" },
            { name: "Chili", form: "Canned", quantity: "80 cups" },
            { name: "Baked Potatoes", form: "Fresh", quantity: "160 potatoes" },
        ],
        notes:
            "A spicy and filling chili served with loaded baked potatoes.",
        vegan: "Lentils (1 lb)",
        vegetarian: "Beans and vegetables (1 lb)",
        glutenFree: "",
        recommendedSides: "Sour Cream",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "Cornbread",
        createdBy: "",
    },
    {
        recipeName: "Macaroni & Cheese w/ Sliced Hot Dog & Cous Cous Salad",
        difficulty: 1,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Macaroni", form: "Dry (packaged)", quantity: "40 lb" },
            { name: "Cheddar Cheese", form: "Pre‐shredded", quantity: "80 cups" },
            { name: "Sliced Hot Dog", form: "Packaged", quantity: "160 pieces" },
            { name: "Cous Cous", form: "Dry (packaged)", quantity: "40 cups" },
        ],
        notes:
            "A fun twist on mac & cheese with hot dogs and a refreshing cous cous salad.",
        vegan: "Vegan sausages (6 pieces) and vegan cheese (3 cups)",
        vegetarian: "Vegetable medley (1 lb)",
        glutenFree:
            "Gluten‑free macaroni (1 lb) and gluten‑free cous cous (1 cup)",
        recommendedSides: "Breadsticks",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName: "Shepards Pie",
        difficulty: 3,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Ground Lamb", form: "Fresh (ground)", quantity: "40 lb" },
            { name: "Mixed Vegetables", form: "Fresh (diced)", quantity: "80 cups" },
            { name: "Mashed Potatoes", form: "Prepared", quantity: "120 cups" },
        ],
        notes:
            "A comforting shepherd's pie with a savory lamb filling and mashed potato topping.",
        vegan: "Lentils (1 lb) and mashed cauliflower (1 lb)",
        vegetarian: "Lentils and extra vegetables (1 lb)",
        glutenFree: "",
        recommendedSides: "",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName:
            "Chicken Noodle Soup & Grilled Cheese & Bacon Sandwiches (disposable bowls)",
        difficulty: 1,
        cost: 2,
        month: 5,
        meal: "dinner",
        ingredients: [
            { name: "Chicken Noodle Soup", form: "Prepared", quantity: "80 cups" },
            { name: "Grilled Cheese", form: "Prepared", quantity: "80 sandwiches" },
            { name: "Bacon Sandwiches", form: "Prepared", quantity: "80 sandwiches" },
        ],
        notes:
            "Comforting soup with grilled cheese and bacon sandwiches served in disposable bowls.",
        vegan:
            "Vegetable soup (3 cups), vegan grilled cheese (3 sandwiches), and vegan bacon (3 pieces)",
        vegetarian:
            "Tomato‐based grilled cheese (3 sandwiches) and smoked tofu (3 pieces)",
        glutenFree: "Gluten‑free bread (as per recipe)",
        recommendedSides: "Saltine Crackers",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName:
            "BBQ Chicken Drumsticks/Thighs w/ corn on the cob & potato salad",
        difficulty: 3,
        cost: 3,
        month: 7,
        meal: "dinner",
        ingredients: [
            { name: "BBQ Chicken Drumsticks", form: "Fresh", quantity: "240 pieces" },
            { name: "Corn on the Cob", form: "Fresh", quantity: "160 cobs" },
            { name: "Potato Salad", form: "Prepared", quantity: "80 cups" },
        ],
        notes:
            "Smoky BBQ chicken paired with corn and a creamy potato salad.",
        vegan: "BBQ jackfruit (9 pieces) and vegan potato salad (3 cups)",
        vegetarian: "Grilled tofu (9 pieces)",
        glutenFree: "",
        recommendedSides: "Coleslaw",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName: "Tacos",
        difficulty: 2,
        cost: 2,
        month: 7,
        meal: "dinner",
        ingredients: [
            { name: "Taco Shells", form: "Hard (packaged)", quantity: "320 shells" },
            { name: "Seasoned Beef", form: "Fresh (ground)", quantity: "40 lb" },
            { name: "Lettuce", form: "Fresh", quantity: "40 cups" },
            { name: "Cheddar Cheese", form: "Pre‐shredded", quantity: "40 cups" },
            { name: "Tomato", form: "Fresh", quantity: "40 tomatoes" },
        ],
        notes:
            "Crunchy tacos loaded with seasoned beef and fresh toppings.",
        vegan: "Black beans (1 lb)",
        vegetarian: "Beans and grilled vegetables (1 lb)",
        glutenFree: "Gluten‑free taco shells (11 shells)",
        recommendedSides: "Guacamole",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "Churros",
        createdBy: "",
    },
    {
        recipeName: "Burritos",
        difficulty: 3,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Flour Tortillas", form: "Packaged", quantity: "240 tortillas" },
            { name: "Refried Beans", form: "Canned", quantity: "40 cups" },
            { name: "Rice", form: "Dry (packaged)", quantity: "80 cups" },
            { name: "Cheese", form: "Pre‐shredded", quantity: "40 cups" },
            { name: "Salsa", form: "Fresh", quantity: "40 cups" },
        ],
        notes:
            "A filling burrito with hearty beans, rice, and cheese.",
        vegan: "Vegan cheese (1 cup)",
        vegetarian: "Already vegetarian",
        glutenFree: "Gluten‑free tortillas (9 tortillas)",
        recommendedSides: "Nachos",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName: "Fajitas",
        difficulty: 3,
        cost: 4,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Chicken or Beef", form: "Fresh (sliced)", quantity: "40 lb" },
            { name: "Bell Peppers", form: "Fresh", quantity: "80 peppers" },
            { name: "Onions", form: "Fresh", quantity: "40 onions" },
            { name: "Fajita Seasoning", form: "Packaged", quantity: "to taste" },
            { name: "Lime", form: "Fresh", quantity: "40 limes" },
        ],
        notes:
            "Sizzling fajitas with vibrant peppers, onions, and tender meat.",
        vegan: "Portobello mushrooms and tofu (1 lb)",
        vegetarian: "Extra vegetables and tofu (1 lb)",
        glutenFree: "",
        recommendedSides: "Guacamole",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "Flan",
        createdBy: "",
    },
    {
        recipeName: "Quesadillas & Mexican Salad",
        difficulty: 2,
        cost: 2,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Tortillas", form: "Packaged", quantity: "160 tortillas" },
            { name: "Cheese", form: "Melted", quantity: "80 cups" },
            { name: "Chicken", form: "Fresh (diced)", quantity: "40 lb" },
            { name: "Mexican Salad", form: "Fresh", quantity: "40 bowls" },
        ],
        notes:
            "Cheesy quesadillas paired with a zesty Mexican salad.",
        vegan: "Seasoned tofu (1 lb) and vegan cheese (3 cups)",
        vegetarian: "Extra vegetables (1 lb)",
        glutenFree: "Gluten‑free tortillas (6 tortillas)",
        recommendedSides: "Sour Cream",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName:
            "Murgh Saagwala (Chicken curry with tomato/onion base and leafy greens)",
        difficulty: 3,
        cost: 3,
        month: 5,
        meal: "dinner",
        ingredients: [
            { name: "Chicken", form: "Fresh (diced)", quantity: "40 lb" },
            { name: "Tomato", form: "Canned (pureed)", quantity: "80 cups" },
            { name: "Onion", form: "Fresh (chopped)", quantity: "40 cups" },
            { name: "Spinach", form: "Fresh", quantity: "120 cups" },
            { name: "Curry Spices", form: "Mixed (packaged)", quantity: "80 tbsp" },
        ],
        notes:
            "A fragrant chicken curry with a rich, spicy tomato base.",
        vegan: "Chickpeas (1 lb)",
        vegetarian: "Paneer or tofu (1 lb)",
        glutenFree: "",
        recommendedSides: "Naan",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "Gulab Jamun",
        createdBy: "",
    },
    {
        recipeName: "Chicken Souvlaki wraps",
        difficulty: 2,
        cost: 3,
        month: 7,
        meal: "dinner",
        ingredients: [
            { name: "Chicken", form: "Fresh (marinated)", quantity: "40 lb" },
            { name: "Pita Bread", form: "Packaged", quantity: "160 pitas" },
            { name: "Tzatziki Sauce", form: "Prepared", quantity: "40 cups" },
            { name: "Lettuce", form: "Fresh", quantity: "40 cups" },
            { name: "Tomato", form: "Fresh (sliced)", quantity: "40 tomatoes" },
        ],
        notes:
            "Greek‐style wraps bursting with flavor and fresh veggies.",
        vegan: "Marinated portobello mushrooms (1 lb) and vegan tzatziki (1 cup)",
        vegetarian: "Grilled vegetables (1 lb)",
        glutenFree: "Gluten‑free pita (6 pitas)",
        recommendedSides: "",
        recommendedBread: "",
        recommendedSalad: "Greek Salad",
        recommendedDessert: "",
        createdBy: "",
    },
    {
        recipeName: "Tandoori Chicken w/ Curried Lentils & Roasted Vegetables",
        difficulty: 3,
        cost: 3,
        month: 6,
        meal: "dinner",
        ingredients: [
            { name: "Tandoori Chicken", form: "Fresh (spiced)", quantity: "40 lb" },
            { name: "Curried Lentils", form: "Prepared", quantity: "80 cups" },
            { name: "Roasted Vegetables", form: "Fresh", quantity: "80 cups" },
        ],
        notes:
            "An Indian‐inspired dish with spiced chicken and aromatic lentils.",
        vegan: "BBQ tofu (1 lb) and curried chickpeas (3 cups)",
        vegetarian: "Extra lentils and vegetables (1 lb)",
        glutenFree: "",
        recommendedSides: "Naan",
        recommendedBread: "",
        recommendedSalad: "",
        recommendedDessert: "Rice Pudding",
        createdBy: "",
    },
];